[workspace]
resolver = "3"
members = [ "crates/keyfinix-comm", "crates/keyfinix-crypto", "crates/keyfinix-derive", "crates/keyfinix-sandboxing", "crates/keyfinix-server","frontend"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "Apache-2.0"
authors = ["MomentQYC <admin@yatserver.com>", "eternal-flame-AD (Yumechi) <yume@yumechi.jp>"]
repository = "https://github.com/Whimsies-YAT/Vickey"
homepage = "https://github.com/Whimsies-YAT/Vickey"

[workspace.dependencies]
aes-gcm = { version = "0.10", default-features = false, features = ["aes", "zeroize"] }
base64 = "0.22"
flate2 = "1"
itertools = "0.14"
siphasher = "1"
mime_guess = "2.0"
proc-macro2 = "1.0"
derive_more = { version = "1", features = ["deref", "from", "display", "try_from", "try_into", "as_ref", "add"] }
quote = "1.0"
sha2 = "0.10"
axum = "0.8"
futures = "0.3"
http = "1"
thiserror = "2.0"
tower = "0.5"
tokio = { version = "1.45", features = ["macros"] }
keyfinix-frontend = { path = "frontend" }
keyfinix-comm = { path = "crates/keyfinix-comm" }
keyfinix-crypto = { path = "crates/keyfinix-crypto" }
keyfinix-sandboxing = { path = "crates/keyfinix-sandboxing" }
keyfinix-derive = { path = "crates/keyfinix-derive" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.5", features = ["derive"] }
url = "2.5"
uuid = "1"
serde = "1.0"
prometheus = "0.14"
chrono = "0.4"
governor = "0.10"
zeroize = "1"
secrecy = "0.10"
parking_lot = "0.12"
tower-service = "0.3"
tracing-log = "0.2"
vergen-gix = { version = "1", features = ["build", "cargo", "rustc"] }