use ::keyfinix_crypto::auth::{AssocEncoder, ScopeAssoc, abstracted::AsBytesAssoc};
use base64::{Engine as _, prelude::BASE64_STANDARD};
#[cfg(feature = "protected-memory")]
use keyfinix_sandboxing::protected_memory::MemFdSecret;
use rand::RngCore;
use secrecy::zeroize::{ZeroizeOnDrop, Zeroizing, zeroize_flat_type};

use crate::database::uops::prelude::*;

use super::*;

const SCOPE_PERSIST_DATABASE_DEK: ScopeAssoc = ScopeAssoc::new("sys:persist-database-dek");

/// Initialization structure for the key store, keyed by a secret key generated by the configuration
pub struct KiyokaInit<A: AeadInPlace + KeyInit + Send + Sync> {
    aead: A,
}

impl<A: AeadInPlace + KeyInit + Send + Sync> KeySizeUser for KiyokaInit<A> {
    type KeySize = <A as KeySizeUser>::KeySize;
}

impl<A: AeadInPlace + KeyInit + Send + Sync> Zeroize for KiyokaInit<A> {
    fn zeroize(&mut self) {
        unsafe { zeroize_flat_type(self) };
    }
}

impl<A: AeadInPlace + KeyInit + Send + Sync> ZeroizeOnDrop for KiyokaInit<A> {}

impl<A: AeadInPlace + KeyInit + Send + Sync> Drop for KiyokaInit<A> {
    fn drop(&mut self) {
        self.zeroize();
    }
}

/// Initialize the key store using the raw DEK (maybe disaster recovery?)
impl<A: AeadInPlace + KeyInit + Send + Sync> KeyInit for KiyokaInit<A> {
    fn new(root_aead: &aes_gcm::Key<Self>) -> Self {
        Self {
            aead: A::new(root_aead),
        }
    }
}

impl<A: AeadInPlace + KeyInit + Send + Sync> KeyStoreInit for KiyokaInit<A> {
    type Service = KiyokaKeyStore<A>;

    async fn list_key_selectors(
        &self,
        db: &impl ConnectionTrait,
    ) -> Result<Vec<(String, String)>, KeyStoreServiceError> {
        let all_keks: Vec<(String, Vec<u8>)> = MetaBlobEntity::find()
            .filter(MetaBlobColumn::Name.like("db-encryption-dek-kiyoka-%"))
            .select_only()
            .column(MetaBlobColumn::Name)
            .column(MetaBlobColumn::Value)
            .into_tuple()
            .all(db)
            .await?;

        Ok(all_keks
            .into_iter()
            .map(|(name, value)| {
                let key_selector = name
                    .strip_prefix("db-encryption-dek-kiyoka-")
                    .unwrap()
                    .to_string();
                let dek = BASE64_STANDARD.encode(value);
                (key_selector, dek)
            })
            .collect())
    }

    async fn reencrypt_dek(
        self,
        self_selector: &str,
        new_init: &Self,
        new_selector: &str,
        db: &impl ConnectionTrait,
    ) -> Result<String, KeyStoreServiceError> {
        let dek_entry_name = compute_dek_db_entry_name("kiyoka", self_selector);

        let data_key_wrapped = MetaBlobEntity::find()
            .filter(MetaBlobColumn::Name.eq(dek_entry_name.clone()))
            .one(db)
            .await?;

        let Some(data_key_wrapped) = data_key_wrapped else {
            tracing::error!("rekey failed: key selector is not valid or database is corrupted");
            return Err(KeyStoreServiceError::UnsealFailed);
        };

        let mut data_key_wrapped = data_key_wrapped.value;

        let mut new_nonce = GenericArray::default();
        {
            let mut rng = rand::rng();
            rng.fill_bytes(&mut new_nonce);
        }

        AssocEncoder::bootstrap()
            .push_assoc(&SCOPE_PERSIST_DATABASE_DEK)
            .rekey(
                &self.aead,
                &new_init.aead,
                &new_nonce,
                &mut data_key_wrapped,
            )
            .map_err(|_| KeyStoreServiceError::UnsealFailed)?;

        let backup_data = BASE64_STANDARD.encode(&data_key_wrapped);

        if self_selector != new_selector {
            let new_dek_entry_name = compute_dek_db_entry_name("kiyoka", new_selector);
            MetaBlobEntity::insert(MetaBlobActiveModel {
                name: Set(new_dek_entry_name),
                value: Set(data_key_wrapped),
            })
            .exec(db)
            .await?;
        } else {
            MetaBlobEntity::update(MetaBlobActiveModel {
                name: Set(dek_entry_name),
                value: Set(data_key_wrapped),
            })
            .exec(db)
            .await?;
        }

        Ok(backup_data)
    }

    async fn insert_dek(
        self,
        key_selector: &str,
        recovery_dek: String,
        db: &impl ConnectionTrait,
    ) -> Result<(), KeyStoreServiceError> {
        let dek_entry_name = compute_dek_db_entry_name("kiyoka", key_selector);

        let recovery_dek = BASE64_STANDARD.decode(&recovery_dek)?;

        MetaBlobEntity::insert(MetaBlobActiveModel {
            name: Set(dek_entry_name),
            value: Set(recovery_dek),
        })
        .exec(db)
        .await?;

        Ok(())
    }

    async fn destroy_dek(
        &self,
        key_selector: &str,
        unchecked: bool,
        db: &impl ConnectionTrait,
    ) -> Result<(), KeyStoreServiceError> {
        let dek_entry_name = compute_dek_db_entry_name("kiyoka", key_selector);

        let data_key_wrapped = MetaBlobEntity::find()
            .filter(MetaBlobColumn::Name.eq(dek_entry_name.clone()))
            .one(db)
            .await?;

        let Some(mut data_key_wrapped) = data_key_wrapped else {
            return Ok(());
        };

        if unchecked {
            rand::rng().fill_bytes(&mut data_key_wrapped.value);
        } else {
            let mut rng = rand::rng();
            let mut random_key = GenericArray::default();
            rng.fill_bytes(&mut random_key);
            let mut random_nonce = GenericArray::default();
            rng.fill_bytes(&mut random_nonce);
            let random_aead = A::new(&random_key);
            AssocEncoder::bootstrap()
                .push_assoc(&SCOPE_PERSIST_DATABASE_DEK)
                .rekey(
                    &self.aead,
                    &random_aead,
                    &random_nonce,
                    &mut data_key_wrapped.value,
                )
                .map_err(|_| KeyStoreServiceError::UnsealFailed)?;

            random_key.zeroize();
            random_nonce.zeroize();
        }

        MetaBlobEntity::update(MetaBlobActiveModel {
            name: Set(dek_entry_name.clone()),
            value: Set(data_key_wrapped.value),
        })
        .exec(db)
        .await?;

        MetaBlobEntity::delete(MetaBlobActiveModel {
            name: Set(dek_entry_name),
            ..Default::default()
        })
        .exec(db)
        .await?;

        Ok(())
    }

    async fn initialize(
        self,
        key_selector: &str,
        db: DbPool,
    ) -> Result<Self::Service, KeyStoreServiceError> {
        let dek_entry_name = compute_dek_db_entry_name("kiyoka", key_selector);

        // the long-term key used to encrypt the database data
        let data_key_wrapped = MetaBlobEntity::find()
            .filter(MetaBlobColumn::Name.eq(dek_entry_name.clone()))
            .one(&*db.get().await)
            .await?;

        #[cfg(feature = "protected-memory")]
        let mut root_keys =
            MemFdSecret::<KiyokaRootKeys<A>>::new(true).expect("failed to create secretmem");

        #[cfg(not(feature = "protected-memory"))]
        let mut root_keys = Zeroizing::new(core::mem::zeroed());

        if let Some(mut data_key_wrapped) = data_key_wrapped.map(|m| Zeroizing::new(m.value)) {
            let dek = AssocEncoder::bootstrap()
                .push_assoc(&SCOPE_PERSIST_DATABASE_DEK)
                .unwrap(&self.aead, &mut data_key_wrapped)
                .map_err(|_| {
                    tracing::error!("DB unseal failed: key is not valid or database is corrupted");
                    KeyStoreServiceError::UnsealFailed
                })?;

            let (db_key, encoder_key) = dek
                .split_at_checked(A::KeySize::USIZE)
                .expect("DB unseal failed: invalid key size");

            core::mem::swap(
                &mut root_keys.aead,
                &mut A::new_from_slice(db_key).expect("DB unseal failed: invalid key size"),
            );
            core::mem::swap(
                &mut root_keys.encoder,
                &mut AssocEncoder::new(
                    u64::from_le_bytes(encoder_key[0..8].try_into().unwrap()),
                    u64::from_le_bytes(encoder_key[8..16].try_into().unwrap()),
                ),
            );
        } else {
            let all_keks = self.list_key_selectors(&*db.get().await).await?;

            if !all_keks.is_empty() {
                tracing::error!(
                    "the key selector '{key_selector}' is not valid: try one of: {all_keks:?}"
                );
                return Err(KeyStoreServiceError::UnsealFailed);
            }

            event!(
                Level::INFO,
                "no database encryption key found, generating a new one."
            );

            let mut assoc_key: [u8; 16] = [0; 16];
            let mut key = GenericArray::default();
            let mut nonce = GenericArray::default();
            {
                let mut rng = rand::rng();
                rng.fill_bytes(&mut assoc_key);
                rng.fill_bytes(&mut key);
                rng.fill_bytes(&mut nonce);
            }
            let mut keypair_wrapped = key.to_vec();
            keypair_wrapped.extend_from_slice(&assoc_key);

            core::mem::replace(
                &mut root_keys.encoder,
                AssocEncoder::new(
                    u64::from_le_bytes(assoc_key[0..8].try_into().unwrap()),
                    u64::from_le_bytes(assoc_key[8..16].try_into().unwrap()),
                ),
            );

            core::mem::replace(&mut root_keys.aead, A::new(&key));
            key.zeroize();

            AssocEncoder::bootstrap()
                .push_assoc(&SCOPE_PERSIST_DATABASE_DEK)
                .wrap(&self.aead, &nonce, &mut keypair_wrapped);

            MetaBlobActiveModel {
                name: Set(dek_entry_name.to_string()),
                value: Set(keypair_wrapped),
            }
            .insert(&*db.get().await)
            .await?;
        }

        Ok(KiyokaKeyStore { root_keys, db })
    }
}

#[derive(Clone)]
struct KiyokaRootKeys<A: AeadInPlace + KeyInit + Send + Sync> {
    aead: A,
    encoder: AssocEncoder,
}

impl<A: AeadInPlace + KeyInit + Send + Sync> Zeroize for KiyokaRootKeys<A> {
    fn zeroize(&mut self) {
        unsafe {
            zeroize_flat_type(self);
        }
    }
}

/// Keystore by the [`::kiyoka`] crate.
pub struct KiyokaKeyStore<A: AeadInPlace + KeyInit + Send + Sync> {
    #[cfg(not(feature = "protected-memory"))]
    root_keys: Zeroizing<KiyokaRootKeys<A>>,
    #[cfg(feature = "protected-memory")]
    root_keys: MemFdSecret<KiyokaRootKeys<A>>,
    db: DbPool,
}

/// Associated data for actor key ID
type KeyIdAssoc<T> = AsBytesAssoc<T, 0xda67_7ba4_b614_4780, 0x8365_5675_54a2_eee7>;

impl<A: AeadInPlace + KeyInit + Send + Sync> KeyStoreService for KiyokaKeyStore<A> {
    type Init = KiyokaInit<A>;

    fn begin_aead(&self, scope: &ScopeAssoc) -> AssocEncoder {
        self.root_keys.encoder.push_assoc(scope)
    }

    fn borrow_cipher(&self) -> &impl AeadInPlace {
        &self.root_keys.aead
    }
}
